version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: farmgame
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    container_name: backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:password@postgres:5432/farmgame?schema=public"
    ports:
      - "3001:3001"

  frontend:
    build: ./apps/frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
